#!/usr/bin/env bash
# Display listening TCP and UDP sockets with PID/Program name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -tulnp | awk 'NR>1 {print $1, $2, $3, $4, $5, $6, $7}' # Exclude header

echo ""
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
ss -x -a | awk 'NR>1 {print $1, $2, $3, $4, $5, $6, $7, $8}' # Exclude header
