#!/usr/bin/env bash
# This script modifies /etc/hosts to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Backup the current hosts file
sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts